# Generated by Django 5.0.6 on 2025-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
